version: "3.5"
services:
  etcd:
    hostname: etcd
    image: bitnami/etcd:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    volumes:
      - "/Users/sean/docker/etcd/data:/bitnami/etcd"# 注意这个目录容器要可写，不然会报cannot access data directory: open
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes" #参数指不用密码可以连接
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
    ports:
      - 2379:2379
      - 2380:2380
  mysql:
    image: mysql #镜像名称以及版本
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    container_name: mysql #容器名称
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #指定用户密码
      TZ: Asia/Shanghai
    ports:
      - 3306:3306 #本地端口号与容器内部端口号
    volumes: #指定挂载目录
      - /Users/sean/docker/mysql/data:/var/lib/mysql
      - /Users/sean/docker/mysql/config/my.cnf:/etc/mysql/my.cnf
  redis: #  1. protected-mode 设置为 no; 2. ignore-warnings ARM64-COW-BUG 注释放开
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    volumes:
      - /Users/sean/docker/redis/data:/data
      - /Users/sean/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379